name: CI

on:
    push:
      branches: [ develop ]
    pull_request:
      branches: [ main, develop ]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
      - name: Initialize Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: python3 -m pip install --editable .[test]
      - name: Run pytest tests
        run: MPLBACKEND=Agg GPSEA_CACHEDIR=.gpsea_ci_cachedir pytest
  
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Initialize Python 3.12
      uses: actions/setup-python@v4.3.1
      with:
        python-version: "3.12"
    - name: Install package
      run: python3 -m pip install --editable .[test]
    - name: Check formatting
      run:  ruff format --check
