name: CI
##
# Add the line below to README.md and the badge will come alive when we make the repo public.
# [![CI](https://github.com/monarch-initiative/genophenocorr/workflows/CI/badge.svg)](https://github.com/monarch-initiative/genophenocorr/actions/workflows/python_ci.yml)

on:
    push:
      branches: [ develop ]
    pull_request:
      branches: [ main, develop ]

jobs:
    build:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os: [ windows-latest, macOS-latest, ubuntu-latest ]

      steps:
        - uses: actions/checkout@v2
        - name: Initialize Python ${{ matrix.python }}
          uses: actions/setup-python@v4.3.1
          with:
            python-version: "3.11"
        - name: Install package
          run: |
            pip install ".[test]"
        - name: Run pytest tests
          run: |
            pytest
