name: CI

on:
    push:
      branches: [ develop ]
    pull_request:
      branches: [ main, develop ]

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ['3.8', '3.9', '3.10', '3.11']

      steps:
        - uses: actions/checkout@v4
        - name: Initialize Python
          uses: actions/setup-python@v4.3.1
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install package
          run: |
            python3 -m pip install --editable .[test,docs]
        - name: Run pytest tests
          run: |
            pytest
        - name: Run documentation tests
          run: |
            cd docs
            sphinx-apidoc --separate --module-first -d 2 -H "API reference" -o apidocs ../src/genophenocorr
            make doctest
